### ISSUE TITLE
☔️🎃 Umbrella Hacktoberfest Issue

### ISSUE THREAD

**Issue by romellogoodman** [onthecompiler/thecompiler#2]
This an umbrella issue for hacktoberfests participants!

Please review [CONTRIBUTING.md](https://github.com/onthecompiler/thecompiler/blob/master/CONTRIBUTING.md) and contribute as much as you would like!

**Comment by frewinchristopher** [comment]
This is a super neat idea! It's like a super fast google for programming resources only! I'll gladly make a PR with all the top links I've found over the years!

A question: is there a way to detect duplicates? (Probably best by URL value)

Anyways, expect a PR soon :smile:

**Comment by romellogoodman** [comment]
@frewinchristopher I haven't figured this out yet but created #7 to kick off a discussion around it

**Comment by romellogoodman** [comment]
Closing because Hacktoberfest is over. Thanks everyone!
